### PR TITLE
Added support for bypassing queueit captchas and added skat.dk flow

### PR DESCRIPTION
**Pull request by helmstedt**
I have added functionality for bypassing Queue-it CAPTCHAs either by using an (untrusted) API (reports 98% success rate) or by using PaddleOCR (about 80% success rate from my experiments, also tried EasyOCR but that had a worse rate).

mit.dk, e-boks and skat.dk regularly/always redirects to these CAPTCHA challenges.

Let me know if you'd like to include this functionality, or if you think it diverts too much from the main functionality...

I have neglected to update requirements.txt. If I recall correctly, I installed PaddleOCR like this:

pip install paddlepaddle
pip install paddleocr

Also added a flow for skat.dk.

Also fixed wording errors on some error messages I encountered while developing :)

### CODE REVIEW

**Comment by Hundter** [comment]
Ok this is crazy @helmstedt, I was literally playing with Queue-it captcha's today too and just pushed my version of it to main, when I saw that you have created this PR earlier today...

That's what I get for not reading my e-mails.

I will take a look at what you have done here, and see if perhaps paddleocr is superior to tesseract. I would say tesseract seems to get the correct answer about 10-33% of the time, but I have retry mechanisms that give 100% success rate.


I will give this a look tomorrow!

**Comment by helmstedt** [comment]
It's great that you're also thinking of bypassing Queue-it. I also tried tesseract, but as I wrote I got the best results with PaddleOCR. I wrote the person with the API who said he trained the model on 80K queue-it CAPTCHAs, so if someone/you is able to train a model, another option is to ship one with the program (which would be nice).

I also got the idea of saving the Queue-it cookies from the program and loading them on next run so the CAPTCHAs will not encountered as often.

**Comment by Hundter** [comment]
I've swapped the bypass_botdetect function to use PaddleOCR, it is vastly superior for sure! I have also decided not to implement the API you found as that is not needed, PaddleOCR seems to always work, atleast after a few tries and Queue-it is very generous with tries.

I don't think there is a need for adding a "queueit" parameter argument as bypass_botdetect should just run whenever necessary, the user does not need to make that decision.

Can you change your PR to reflect these changes, and use "bypass_botdetect" in skatdk.py in the same way as I've done in mitdk.py and e-boks.py.

Of course feel free to make changes to the "bypass_botdetect" function, but I think it is pretty usable and generic now.

**Comment by helmstedt** [comment]
New commit with skat.dk flow and fix for the few wording errors in browserclient. I agree about the argument decision; I felt it was necessary if the API call to somewhere untrusted was still part of the script.

In the skat.dk script I only import bypass_botdetect if necessary, since on my machine importing paddleocr makes the script significantly slower.

**Comment by Hundter** [comment]
Awesome, merged! I will move the PaddleOCR import in bypass_botdetect, good catch!

**Pull request merged**
